spring.application.name=api-gateway
server.port=8888


eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#enable dynamic routing
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/registry/eureka

#to convert URL to lowercase
spring.cloud.gateway.discovery.locator.lower-case-service-id=true



spring.config.import=${SPRING_CONFIG_IMPORT:optional:configserver:http://config-server:9999/config}




# Route: auth-service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth-service/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=tracking-service
spring.cloud.gateway.routes[1].uri=lb://tracking-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/tracking-service/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[2].id=admin-service
spring.cloud.gateway.routes[2].uri=lb://admin-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/admin-service/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[3].id=delivery-service
spring.cloud.gateway.routes[3].uri=lb://delivery-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/delivery-service/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1

# Route: auth-service swagger docs


spring.cloud.gateway.routes[4].id=auth-service-docs
spring.cloud.gateway.routes[4].uri=lb://auth-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/v3/api-docs/auth-service
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/v3/api-docs/auth-service, /v3/api-docs

spring.cloud.gateway.routes[5].id=tracking-service-docs
spring.cloud.gateway.routes[5].uri=lb://tracking-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/v3/api-docs/tracking-service
spring.cloud.gateway.routes[5].filters[0]=RewritePath=/v3/api-docs/tracking-service, /v3/api-docs

spring.cloud.gateway.routes[6].id=admin-service-docs
spring.cloud.gateway.routes[6].uri=lb://admin-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/v3/api-docs/admin-service
spring.cloud.gateway.routes[6].filters[0]=RewritePath=/v3/api-docs/admin-service, /v3/api-docs

spring.cloud.gateway.routes[7].id=delivery-service-docs
spring.cloud.gateway.routes[7].uri=lb://delivery-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/v3/api-docs/delivery-service
spring.cloud.gateway.routes[7].filters[0]=RewritePath=/v3/api-docs/delivery-service, /v3/api-docs



# Springdoc

springdoc.api-docs.path=/v3/api-docs/gateway
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.config-url=/v3/api-docs/gateway/swagger-config

springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/v3/api-docs/auth-service
springdoc.swagger-ui.urls[1].name=Tracking Service
springdoc.swagger-ui.urls[1].url=/v3/api-docs/tracking-service
springdoc.swagger-ui.urls[2].name=Admin Service
springdoc.swagger-ui.urls[2].url=/v3/api-docs/admin-service
springdoc.swagger-ui.urls[3].name=Delivery Service
springdoc.swagger-ui.urls[3].url=/v3/api-docs/delivery-service

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=false

# Add these lines to gateway properties
spring.cloud.gateway.x-forwarded.enabled=true
spring.cloud.gateway.x-forwarded.for-enabled=true
spring.cloud.gateway.x-forwarded.host-enabled=true
spring.cloud.gateway.x-forwarded.port-enabled=true
spring.cloud.gateway.x-forwarded.proto-enabled=true
spring.cloud.gateway.x-forwarded.prefix-enabled=true

