spring.application.name=admin-service


server.port=8084


#redis properties
spring.cache.type=redis
spring.redis.host=redis
spring.redis.port=6379

#spring.config.import=optional:configserver:http://localhost:9999/config
spring.config.import=${SPRING_CONFIG_IMPORT:optional:configserver:http://config-server:9999/config}

eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/registry/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=false

springdoc.override-with-generic-response=false
server.forward-headers-strategy=framework

springdoc.swagger-ui.use-root-path=true


#this tells 100% of requests will be traced
management.tracing.sampling.probability=1.0
#this tells Send tracing data to the Zipkin server.
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

