spring.application.name=Delivery-service
server.port=8082


spring.datasource.url= jdbc:postgresql://localhost:5432/DeliveryServiceDatabase
spring.datasource.username=postgres
spring.datasource.password=root
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=true
#
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

#eureka.client.serviceUrl.defaultZone=http://localhost:8761/registry/eureka

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.config.import=optional:configserver:http://localhost:9999/config

